### ISSUE TITLE
Support Specifying book code in URL

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/book-package-app#1]
We need persistent URLs to any book selection allowed in the app's UI.

e.g. something like, `/bp=rut` and `/bp=rut,jon,tit` and `/bp=nt`, etc.

**Comment by mandolyte** [comment]
Based on some experiments over at `https://mandolyte.github.io/rrouter/`, this cannot be done (unless I misunderstand what is described here). Persistent URLs imply that they can be executed with curl. So while this works in a browser (where there is a javascript engine to actually do something):
`https://mandolyte.github.io/rrouter/download?books=1jn,2jn,3jn&format=csv`

this does not:
curl -X GET https://mandolyte.github.io/rrouter/download?books=1jn,2jn,3jn&format=csv

Without something like nginx we can't make a true RESTful API for our 2 Tier style applications. In other words a URL like `https://unfoldingword.github.io/book-package-app/download/bp=rut` cannot work.

However, params will work ok, thus this:
`https://unfoldingword.github.io/book-package-app/?bp=rut&download=true`

@jag3773
