### ISSUE TITLE
Support permalinks with URL params

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/book-package-app#13]
It would be nice to be able to share a link to a "recipe" by using URL parameters to specify what books are being used.  For an example, you can see the translation helps prototype:

https://unfoldingword-box3.github.io/translation-helps/?owner=door43-catalog&rc=/en/ult/gen/1

In our case we might want compatibility with tC Create patterns listed in https://github.com/unfoldingWord/tc-create-app/issues/28 ?

It may depend on whether gitea react toolkit supports any of this?

Anyway, we'd at least need to be able to support the DCS owner to look at (unfoldingWord right now), and then also a list of books to review.  It could be as simple as

* `owner`
* `books`

Looking like this: `/?owner=unfoldingword&books=gen,exo`

You'd want to app to update the URL when the user navigates, too.

**Comment by mandolyte** [comment]
During the discussion on this, I thought the idea was to embed a URL into a spreadsheet cell. When the URL was executed it would return a single number (not even JSON, much less a web page). In that case, this URL:
`https://unfoldingword.github.io/book-package-app/all?books=gen,exo`
would return a single number.

And maybe:
`https://unfoldingword.github.io/book-package-app/tn?books=gen,exo`
would return the total contributed by just the notes.

And for details, this:
`https://unfoldingword.github.io/book-package-app/ta/csv?books=gen,exo`
might return all the UTA articles used by the books with counts as a CSV file.

Thoughts? @jag3773

**Comment by jag3773** [comment]
@mandolyte this is a distinct issue from what Russ was requesting. I think we solve Russ' request by #15 . This one is to make it easier for people to share their research.

**Comment by mandolyte** [comment]
@jag3773 At present, the `unfoldingword` account is hard-coded. It was that way with the code I borrowed from Klappy and the RCL doesn't take it as a parameter. So for the first pass at this, I'll ignore this part.

So this leaves a query parameter consisting solely of the books part: `books=gen,exo`.

You had a comment at the very end, namely, "You'd want to app to update the URL when the user navigates, too." This sounds like you want a feature to allow a person to get the URL for their selections. How about a button in the menu drawer that says something like "Share Book Package"?

If clicked, what should happen? Alternatives:
- copy the URL to the clipboard
- popup a dialog showing the URL and let user look at it, select, and copy.

Not sure "share" is the right word for either of the above. On my phone, share sends me to another app with the info... not sure that this is possible on the web (or that we'd want to).

**Comment by jag3773** [comment]
I like the button idea @mandolyte , I suspect that will be more user friendly for non-techies.  I think a tooltip sort of pop-up when you click on it would be better than the web page dialog.

Let's just label the button "Copy Link".

One more request, can we get `nt` and `ot` as valid parameters for `books` ?  That way the selection of all the OT or all the NT is more easily referenced?

**Comment by mandolyte** [comment]
Switch to the "popover" to replace the alert is done.

However, I don't think allowing entire OT and NT will work... at least not without some work. I generally split up the packages into Pentateuch sized chunks and it takes a while to complete. I just tried to do the entire NT and below happened. I think to do large packages, I need a way to pace things to keep from overwhelming the server. Thoughts/advice? @jag3773 @klappy 
```
UTQ Error on:https://git.door43.org/api/v1/repos/unfoldingword/en_tq/contents/php/01 is:Error: Network Error
Network Error
Network Error
fetchBookPackageTw() Error: Network Error
Network Error
fetchBookPackageTa() Error: Network Error
UTQ Error on:https://git.door43.org/api/v1/repos/unfoldingword/en_tq/contents/rev/01 is:Error: Network Error
Network Error
Network Error
fetchBookPackageTw() Error: Network Error
Network Error
fetchBookPackageTa() Error: Network Error
```

**Comment by mandolyte** [comment]
@jag3773 Since the change to allow nt and ot as parameters is a separate and distinct issue, I'm going to close this one and make new one that only has that in it.
