### ISSUE TITLE
Add resource based totals

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/book-package-app#14]
At the top of step two we have the book packages total. It would also be helpful to list down the resource totals (UTN word count for all BPs selected) for all of the book packages selected.

**Comment by mandolyte** [comment]
This is actually a change to the RCL. It is complete with `book-package-rcl version 1.1.6`. Looks like this:
```
Total Word Count 59366
ULT Total 953
UST Total 1734
UTN Total 4338
UTQ Total 784
UTW Total 33378
UTA Total 18179
```
The sum of the resource totals should equal the `Total Word Count`... thus:
`59366 = 953 + 1734 + 4338 + 784 + 33378 + 18179`

@jag3773
