### ISSUE TITLE
Add spreadsheet export

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/book-package-app#15]
In step two, there should be a button to download a csv file of the word count data. The csv file should have the following columns:

> book,ult,ust,utn,utq,utw,uta

An example row would be:

> 3jn,312,527,1029,320,10206,10509

Note that ALL books of the Bible should always be included, in canonical order. Books not selected should show blank values.

Name the button "Export".

**Comment by mandolyte** [comment]
Completed. Note that only selected book data is exported. Otherwise, the data cannot be copy/pasted without overwriting existing data.
