### ISSUE TITLE
Electron copy link problem

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/book-package-app#21]
When running as standalone as Electron app, the copy link yields something like this:
`file:///C:/Users/mando/AppData/Local/Programs/book-package-app/resources/app.asar/app/index.html?books=1jn,2jn,3jn`

The link should be something like:
`https://unfoldingword.github.io/book-package-app/?books=1jn,2jn,3jn`

So the fix is to examine the base for a link that begins with `file://` and use the online base instead.

**Comment by jag3773** [comment]
works and looks great!
