### ISSUE TITLE
Add OBS resources to the Book Package App 

### ISSUE THREAD

**Issue by BincyJ** [unfoldingWord/book-package-app#30]
Need the OBS resources in the new tsv file format (https://git.door43.org/unfoldingWord/en_translation-annotations/src/branch/master/obs/obs_twl.tsv) to be added to the OBS app.

**Comment by mandolyte** [comment]
@BincyJ The note above alludes to the TSV formats that are coming. Since they aren't here yet, should I proceed with the current way of doing things (see snippet below) or treat this as a blocker?

The resources for OBS are in lots of places at present:
![image](https://user-images.githubusercontent.com/1289437/95765431-de023a80-0c7f-11eb-8d29-23af535b0b05.png)

**Comment by mandolyte** [comment]
**Here are questions about the requirements below:**

- Should the files in the front and back folders be included?
- Please confirm that for tN and tQ, that only the words in the Annotation columns are to be counted.
- Please confirm that for the `twl` file, no words are to be counted in the file itself.

**Here are the requirements for uW's English OBS:**

- The OBS content itself is in: https://git.door43.org/unfoldingWord/en_obs/src/branch/master/content
    - The content consists of 50 markdown files and...
    - Two folders named front and back
    - The `front` folder contains:
        - title.md
        - intro.md
    - The `back` folder contains:
        - intro.md
- The resources for OBS are in https://git.door43.org/unfoldingWord/en_translation-annotations/src/branch/master/OBS
- These resources consist of:
    - OBS_tn.tsv
    - OBS_tq.tsv
    - OBS_twl.tsv

The translation notes resource is in TSV format. 
The last column is "Annotation". 
This is the only column on which BPA should do word counts. (TBC).

The translation questions resources is in TSV format.
Again, the last column is "Annotation" and it the column to be counted.

The translation words link resource is in TSV format.
This file aligns the tW articles to the text.
No words are to be counted in this linking file itself.
There is a Support Reference column which has a resource container link
to the article that should be counted.
Articles should only be counted once and the articles can be referenced
many times within this linking file.
An example link is: `rc://*/tw/dict/bible/kt/bless`.
The only valid context for the book package app today is unfoldingWord's English content.
Therefore the the location of the "bless" article will be a combination of:
- the link to the repo: `https://git.door43.org/unfoldingWord/en_tw/src/branch/master/bible` (note this is an HTML link, not the link used for the tool)
- the category folder: `kt` (there two other categories: `names` and `other`)
- the article itself: `bless.md`

The complete tool article link would be:
https://git.door43.org/unfoldingWord/en_tw/raw/branch/master/bible/kt/bless.md

NOTE! There are no translation academy articles associated the OBS, so no need to count any of this resource type.
Similarly, there are no Literal or Simplified Text resources.

**Comment by birchamp** [comment]
@mandolyte 
1) Hmmm.... @jag3773 It looks like the file in the Front should be translated. Is that correct? https://git.door43.org/unfoldingWord/en_obs/src/branch/master/content/front/intro.md

2) yes, only the annotation
3) only the words in the TW markdown files need to be counted.

**Comment by jag3773** [comment]
Yes, everything in `content` should be translatable.
