### ISSUE TITLE
Possible misinterpretation of "unique" word counts

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/book-package-app#4]
The unique word count is subject to misinterpretation, namely, is it an indicator of effort or is it a measure of complexity of vocabulary. It isn't the first, but the second.

Question: given this possible misapplication, should we avoid showing it?

@jag3773

**Comment by jag3773** [comment]
I think the redesign in https://github.com/unfoldingWord/book-package-rcl/issues/39 appropriately de prioritizes the display of the information but still leaves it accessible in the table if someone is looking for it.
