### ISSUE TITLE
Count Inflation

### ISSUE THREAD

**Issue by mandolyte** [unfoldingWord/book-package-app#5]
Some books have high numbers of names and places which are covered by translation word articles. This makes the word counts higher than expected. Would it be of value to allow an option to ignore this source of word counts?

This source is https://git.door43.org/unfoldingWord/en_tw/src/branch/master/bible/names.

@jag3773

**Comment by jag3773** [comment]
This will have to be subject to our discussion of phases/stages of book packages.  Let's wait until we have some discussions on that first.
