### ISSUE TITLE
Book Package Details

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/book-package-app#8]
Use the following as a template for modify Step 2 in the app.  First, let's title it "Book Package Details" in the stepper.

## Instructions

The instructions on the page are actually the instructions for step 3, Optimize.  I wonder if we can move all of it to Step 3? See other issue for notes on this.  So this section would just have the Back | Next buttons on it.

## BP Information

Re-flow the BP information using the following as an example, using 1 and 2 John.  I'm thinking of something like Tree View https://material-ui.com/components/tree-view/.  Note the order of the resources below too.

---

## > Book Packages Total Word Count: **72,932**

When expanded, it would reveal these *indented*:

### > 2 John Book Package Word Count: **20,668**

When those are expanded, they would reveal each component (*indented*), which would also be a dropdown.  I've expanded them in the example below so I don't have to repeat them twice.

#### ⌄ ULT Word Count: **319**

[Word Frequency Table]

#### ⌄ UST Word Count: **498**

[Word Frequency Table]

#### ⌄ Translation Academy Word Count: **7,373**

*Linked modules: **7 unique**, 14 total links*
[Table of links]

#### ⌄ Translation Words Word Count: **11,254**

*Linked articles: **37 unique**, 69 total links*
[Table of links]

#### ⌄ Translation Notes Word Count: **936**

*Number of Notes: **33***
[Word Frequency Table]

#### ⌄ Translation Questions Word Count: **11,254**

*Number of Questions: **11***
[Word Frequency Table]

**Comment by mandolyte** [comment]
The UI design using a tree view is a change to the RCL, not the app. Can you move that part out of this issue?
@jag3773

**Comment by mandolyte** [comment]
About the instructions and the stepper flow... it is easy to move the check boxes about marking completed books to the last step. However, it feels weird. Here's why:
- on the BP details page, you only see a back and next button; with no reason why you should click the next. Of course, I can put language there, but I'm describing something you can't see (yet).
- when you click that next button, the optimization immediately starts off and processes as if no books are marked as completed --- which of course, none aren't (yet).
- then each time you click one, the optimization starts again.

The docs https://material-ui.com/components/steppers/ show all the buttons being used to manage the linear workflow that the stepper represents. Culminating in the final step where all your inputs in the prior steps are used to produce the result.

So to keep in the spirit of the stepper philosophy, I think it would be more natural to introduce a new step where the completed books are selected, then click next to see the (finished) result in a new step 4.

Thoughts? 
@jag3773

**Comment by jag3773** [comment]
I see what you are saying @mandolyte... The problem is that we really have 2 end goals here. The first end goal is step 2 which may be all the user cares about and the instructions for the next step get in the way of reviewing the information presented.

Another option would be to figure out a way to integrate "Optimize" as a flag that shows up on the first step.

Or, we could add a fourth step and put the instructions for Optimize in Step 3.  So we'd have:

1. Select books to calculate BP size
2. Display BP size
3. Select subset of books to optimize
4. Display optimal path

**Comment by mandolyte** [comment]
Moved to issue 39 in book package rcl

@jag3773

**Comment by jag3773** [comment]
https://github.com/unfoldingWord/book-package-rcl/issues/39

**Comment by jag3773** [comment]
I missed this when reviewing the issue, but we are missing the BP counts as in my mockup above.  I'm referring to the word count size for the individual book package, as in:

### > 1 John Book Package Word Count: **61,135**

### > 2 John Book Package Word Count: **20,668**


Currently, the app only shows the title and not a word count number.

**Comment by jag3773** [comment]
OK, is showing that number just below the header easier?  That would be acceptable.

**Comment by mandolyte** [comment]
Done! As originally described above. Took advantage of a React Typography element, which can take custom elements as children. The new element is `<SinglePackageTotal />`.
