### ISSUE TITLE
Design Tweaks

### ISSUE THREAD

**Issue by jag3773** [unfoldingWord/book-package-app#9]
Here's a list of several design tweaks, let me know if you need more info for any of these... some are negotiable if need be :)

## Overall

* [x] Use the uW logo for the favicon
* [x] Set a margin on the whole screen so that stuff doesn't bump the edges... maybe something like `margin: 3%`.
* [x] Center the divs below the stepper.  May need to specify something like max width of 600px or something?
* [x] Center the navigation (Back, Next, Reset) and everything above it
* [x] Add a header bar with a menu and put the "Refresh Book Package Data" toggle in that menu.
* [ ] Do *not* use the book short codes anywhere... e.g. always say "1 John" not "1jn"
* [ ] Let's try to only say **total** when we are providing a roll up total... so we might only see "total word count" once on a page.
* [x] Use commas for the thousands separator, e.g. (60,000)

For the above, see the overall layout of https://create.translationcore.com. Gray background like that app has helps with visual contrast too.

## Step 1

* [x] List the books of the Bible in two columns, start column 2 with NT

## Step 2

* [x] During calculation stage, show a loading type of spinner until all the data is available, then reveal.

See more notes in #8

## Step 3

* [x] Instructions for this step should appear on this page
* [x] Remove "Select any books completed, then click Next to optimize book package flow"
* [x] The instructions label for the check boxes should say "Check completed book packages or none"
* [x] There should be an "Optimize Flow" button to start the calculation
* [x] On button press there should be a loading type of spinner just like in step 2
* [x] Display the resulting output like this (not unordered list for completed BPs and ordered list for flow suggestion):

### Book Package Flow Optimization

If these Book Packages are completed:

* Titus (Book Package Word Count: 59,929)
* 1 John (Book Package Word Count: 61,135)

Proceed in this order:

1. 2 John–Adjusted Book Package Word Count: **3,554**
2. 3 John–Adjusted Book Package Word Count: **4,132**

**Comment by mandolyte** [comment]
@jag3773 Some of the above are RCL changes. I'll move them. I have completed the others, but suspect more refinements will be needed. 

At any rate, to keep things simple, I'll close this issue and let's make new ones for further work.

**Comment by jag3773** [comment]
https://github.com/unfoldingWord/book-package-rcl/issues/37 and https://github.com/unfoldingWord/book-package-rcl/issues/38
